import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "BS BRAND",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="en">
  <body
    style={{
      backgroundImage: "linear-gradient(linear-gradient(to top, #dfe9f3 0%, white 100%)",
      backgroundColor: "black",
      color: "black",
    }}
    className="antialiased"
  >
    {children}
  </body>
</html>
);
}
